DROP DATABASE IF EXISTS beerorderservice;

DROP USER `beer_order_svc`@`%`;

CREATE DATABASE IF NOT EXISTS beerorderservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER `beer_order_svc`@`%` IDENTIFIED  BY 'password';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `beerorderservice`.* TO `beer_order_svc`@`%`;

FLUSH PRIVILEGES;